### PR TITLE
Update dbus-i2c.py

### PR DESCRIPTION
**Pull request by Mattteburk**

### CODE REVIEW

**Comment by Rikkert-RS** [comment]
Hello, what is your concern about adding this change here. This will delete features!

**Comment by Mattteburk** [comment]
Hi  so sorry , I’m a newbie in this  trying to learn.

I wanted to delete rpi temp  and  enable ADC 
Im out on slippery ice so I was not supposed to delete anything….
/Mattias

**Comment by Rikkert-RS** [comment]
ok I will then close this pull request. If you just want to unlock or lock the features, it's best to do this in the local installation or in your fork on Github. An pull request would also bounce back to my repo. See the Readme for how to turn features on/off.

best regards Rickert RS

**Comment by Mattteburk** [comment]
Ok thanxSorry for Making any trouble.Happy new Year !Skickat från min iPhone1 jan. 2024 kl. 14:58 skrev Rikkert-RS ***@***.***>:﻿
ok I will then close this pull request. If you just want to unlock or lock the features, it's best to do this in the local installation or in your fork on Github. An pull request would also bounce back to my repo. See the Readme for how to turn features on/off.
best regards Rickert RS

**Comment by Rikkert-RS** [comment]
image

you need only comment/uncomment these lines to change feature modes

**Pull request closed without merging**
